# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  add3backend:
    image: add3backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7654:7654
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
